import { test, expect } from '@playwright/test';

/**
 * Auto-generated by visual-testing skill (playwright-vr-baseline).
 * Re-generate with: node ~/.claude/skills/visual-testing/scripts/playwright-vr-baseline.mjs
 *
 * First run (seed baselines):
 *   pnpm playwright test tests/visual-regression.spec.ts --update-snapshots
 * Subsequent runs (diff against baseline):
 *   pnpm playwright test tests/visual-regression.spec.ts
 *
 * Baselines live in tests/visual-regression.spec.ts-snapshots/ — commit them.
 */

const BASE = 'http://localhost:4321/opentier';
const MAX_DIFF = 0.01;
const THRESHOLD = 0.2;

test('_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('catalog_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/catalog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('catalog_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('category_ai_apis_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/category/ai-apis`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('category_ai_apis_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_groq_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/service/groq`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_groq_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('service_anthropic_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/service/anthropic`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('service_anthropic_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('compare_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/compare`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('compare_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('sponsors_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/sponsors`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('sponsors_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('state_of_free_tiers_2026_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/state-of-free-tiers/2026`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('state_of_free_tiers_2026_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('methodology_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/methodology`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('methodology_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('changelog_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/changelog`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('changelog_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('legal_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/legal`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('legal_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('submit_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/submit`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('submit_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('about_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/about`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('about_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_desktop_light', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_desktop_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_desktop_dark', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_desktop_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_tablet_light', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_tablet_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_tablet_dark', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_tablet_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_mobile_light', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'light'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_mobile_light.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});

test('v5_preview_mobile_dark', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE}/v5-preview`, { waitUntil: 'domcontentloaded' });
  await page.evaluate(() => { try { localStorage.setItem('opentier-theme', 'dark'); } catch {} });
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('main', { timeout: 5000 }).catch(() => {});
  await page.waitForTimeout(400);
  await expect(page).toHaveScreenshot('v5_preview_mobile_dark.png', {
    fullPage: false,
    maxDiffPixelRatio: MAX_DIFF,
    threshold: THRESHOLD,
  });
});
