name: Check Links
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 200,301,302,403,429 --exclude-mail '**/*.md'
          fail: false
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: link-report
          path: lychee/out.md
          retention-days: 30
